# This is a basic workflow to help you get started with Actions

name: Secrets and variables

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-environment jobs:  
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
       uses: actions/checkout@v4
       
   
        
      

    
