# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev # This job will use variables/secrets from the 'dev' environment
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to dev environment with ${{ vars.Firstkey }}"

  deploy_prod:
    runs-on: ubuntu-latest
    environment: prod # This job will use variables/secrets from the 'prod' environment
    steps:
      - name: Deploy to Prod
        run: echo "Deploying to prod environment with ${{ secrets.DB_PASSWORD_PROD }}"
